In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import json
import requests
import pymysql
import numpy as np
import pandas as pd
import pyspark.pandas as ps
import pyspark.sql.functions as F
from scipy import stats
from pca import pca

WARNING:root:'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.

In [3]:
df_pandas = pd.read_csv("D:/Jupyterfiles/晶合MVAFDC_general开发/MVAanlysisDevelop/inline_algorithm/inline_case5.csv")
df_pandas

,WAFER_ID,OPE_NO,INLINE_PARAMETER_ID,MEASURE_TIME,RANGE_INDEX,FAB_ID,PRODUCT_ID,LOT_ID,AVERAGE,MAX_VAL,...,RANGE,ACT_CODE,ETL_INSERT_TIME,ETL_ARC_FLAG,ETL_BATCH_SYNC_TS,ETL_DEL_FLAG,ETL_DS_JOB_NM,ETL_SRC_DB,ETL_SRC_TBL,ETL_TBL_OPER_TS
0,NAZ439-03,1F.FQE10,CXS1,2023-01-31 22:52:24,0,N1,AFPNM301N.0A01,NAZ439000,0.000000,144.06000,...,288.120000,NaN,2023-05-29 06:00:43,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
1,NAZ439-03,1F.FQE10,CYS1,2023-01-31 22:52:24,0,N1,AFPNM301N.0A01,NAZ439000,0.287947,144.06000,...,283.220490,NaN,2023-05-29 06:00:43,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
2,NAZ439-03,1F.FQE10,FDS1,2023-01-31 22:52:24,0,N1,AFPNM301N.0A01,NAZ439000,0.993052,0.99309,...,0.000082,NaN,2023-05-29 06:00:43,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
3,NAZ439-03,1F.FQE10,TAW1,2023-01-31 22:52:24,0,N1,AFPNM301N.0A01,NAZ439000,109.251900,NaN,...,NaN,NaN,2023-05-29 06:00:43,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
4,NAZ439-03,1F.FQE10,TAWB,2023-01-31 22:52:24,0,N1,AFPNM301N.0A01,NAZ439000,109.251900,NaN,...,NaN,NaN,2023-05-29 06:00:43,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32273,NAZ703-01,1U.PQA10,MCW0,2023-03-30 06:36:50,0,N1,AFPNM301N.0B01,NAZ703050,0.000000,NaN,...,NaN,NaN,2023-05-29 07:42:52,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
32274,NAZ703-01,1U.PQA10,MEW0,2023-03-30 06:36:50,0,N1,AFPNM301N.0B01,NAZ703050,0.000000,NaN,...,NaN,NaN,2023-05-29 07:42:52,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
32275,NAZ703-01,1U.PQA10,MFW0,2023-03-30 06:36:50,0,N1,AFPNM301N.0B01,NAZ703050,1.000000,NaN,...,NaN,NaN,2023-05-29 07:42:52,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
32276,NAZ703-01,1U.PQA10,MSW0,2023-03-30 06:36:50,0,N1,AFPNM301N.0B01,NAZ703050,1.000000,NaN,...,NaN,NaN,2023-05-29 07:42:52,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00
32277,NAZ703-01,1U.PQA10,SNW0,2023-03-30 06:36:50,0,N1,AFPNM301N.0B01,NAZ703050,1.000000,NaN,...,NaN,NaN,2023-05-29 07:42:52,0,1970-01-01 00:00:00,0,NaN,EDA,INLINE_WAFER_SUMMARY,1970-01-01 00:00:00

In [4]:
# df_pandas[df_pandas['OPE_NO'] == '1V.EQW20'][['WAFER_ID', 'OPE_NO', 'INLINE_PARAMETER_ID', 'AVERAGE', 'MAX_VAL', 'MEDIAN', 'MIN_VAL', 'STD_DEV', 
#                 'PERCENTILE_25', 'PERCENTILE_75', 'SITE_COUNT']]

In [5]:
# df1 = df_pandas[df_pandas['OPE_NO'] == '1V.EQW20']
# print(df1.shape)

# df1[df1.columns[df1.columns.str.contains('SITE')]].isna().sum().sort_values()

In [6]:
def select_columns(df, columns_list):
    return df[columns_list]


def get_label(x, good_wafer, bad_wafer):
    if x in good_wafer:
        return 0
    elif x in bad_wafer:
        return 1
    else:
        return 'Nolabel'

    
def run_get_label(df, good_wafer, bad_wafer):
    df['label'] = df['WAFER_ID'].apply(lambda x: get_label(x, good_wafer, bad_wafer))
    df = df[df['label'] != 'Nolabel']
    return df

In [7]:
columns_list = ['WAFER_ID', 'OPE_NO', 'INLINE_PARAMETER_ID', 'AVERAGE', 'MAX_VAL', 'MEDIAN', 'MIN_VAL', 'STD_DEV', 
                'PERCENTILE_25', 'PERCENTILE_75', 'SITE_COUNT']
df_pandas_select = select_columns(df_pandas, columns_list)
print(df_pandas_select.shape)

(32278, 11)

In [8]:
good_wafer = ['NAZ439-03', 'NAZ439-07']
bad_wafer = ['NAZ415-06', 'NAZ415-08', 'NAZ415-12', 'NAZ415-13', 'NAZ439-06', 'NAZ703-01', 
             'NAZ703-08', 'NAZ703-09', 'NBX082-05', 'NBX082-12', 'NBX082-15', 'NBX082-16', 'NBX219-17']
    
df_pandas_select = run_get_label(df_pandas_select, good_wafer, bad_wafer)
df_pandas_select.shape

(32278, 12)

In [9]:
# df_pandas_select = df_pandas[['WAFER_ID', 'OPE_NO', 'INLINE_PARAMETER_ID', 'AVERAGE', 'MAX_VAL',
#        'MEDIAN', 'MIN_VAL', 'STD_DEV', 'PERCENTILE_25', 'PERCENTILE_75',
#        'SITE_COUNT', 'SITE1_VAL', 'SITE2_VAL', 'SITE3_VAL', 'SITE4_VAL',
#        'SITE5_VAL', 'SITE6_VAL', 'SITE7_VAL', 'SITE8_VAL', 'SITE9_VAL',
#        'SITE10_VAL', 'SITE11_VAL', 'SITE12_VAL', 'SITE13_VAL', 'SITE14_VAL', 'SITE15_VAL', 'SITE16_VAL', 'SITE17_VAL', 'label']]

# df_pandas_select['SITE_COUNT'] = df_pandas_select['SITE_COUNT'].astype(float)
# df_pandas_select.shape

# df_pandas_select[df_pandas_select['INLINE_PARAMETER_ID'] == 'FDS1'].shape
# df_pandas_select[~df_pandas_select['INLINE_PARAMETER_ID'].str.contains('CXS|CYS|FDS')]

In [10]:
def exclude_some_data(df, certain_column: str, key_words:list[str]):
    key_words_str = '|'.join(key_words)
    df = df[~df[certain_column].str.contains(key_words_str)]
    return df

In [11]:
df_pandas_select = exclude_some_data(df=df_pandas_select, 
                                      certain_column='INLINE_PARAMETER_ID',
                                      key_words=['CXS', 'CYS', 'FDS'])
df_pandas_select.shape

(32083, 12)

In [12]:
df_pandas_select

,WAFER_ID,OPE_NO,INLINE_PARAMETER_ID,AVERAGE,MAX_VAL,MEDIAN,MIN_VAL,STD_DEV,PERCENTILE_25,PERCENTILE_75,SITE_COUNT,label
3,NAZ439-03,1F.FQE10,TAW1,109.251900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NAZ439-03,1F.FQE10,TAWB,109.251900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,NAZ439-03,1F.FQE10,TDS0,108.411700,108.4117,108.4117,108.4117,0.000000,108.4117,108.4117,1.0,0
6,NAZ439-03,1F.FQE10,TDS1,109.251924,110.1915,109.1703,108.4117,0.547566,108.8124,109.7011,17.0,0
7,NAZ439-03,1F.FQE10,THW1,110.191500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
32273,NAZ703-01,1U.PQA10,MCW0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
32274,NAZ703-01,1U.PQA10,MEW0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
32275,NAZ703-01,1U.PQA10,MFW0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
32276,NAZ703-01,1U.PQA10,MSW0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
32277,NAZ703-01,1U.PQA10,SNW0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [13]:
def pre_process(df, convert_to_numeric_list):
    
    # 数据类型转换
    df[convert_to_numeric_list] = df[convert_to_numeric_list].apply(pd.to_numeric)
    
    # 七个统计值都为NA时，删除这些数据
    if 'SITE_COUNT' in convert_to_numeric_list:
        convert_to_numeric_list.remove('SITE_COUNT')
    df = df.dropna(subset=convert_to_numeric_list, axis=0, how='all')

    # 缺失值填充
#     new_df[agg_list] = new_df[agg_list].apply(lambda x: x.fillna(x.mean()))

    return df

In [14]:
convert_to_numeric_list = ['AVERAGE', 'MAX_VAL', 'MEDIAN', 'MIN_VAL', 'STD_DEV', 'PERCENTILE_25', 'PERCENTILE_75', 'SITE_COUNT']
df_pandas_select = pre_process(df_pandas_select, convert_to_numeric_list)
df_pandas_select.shape

(31791, 12)

In [15]:
df_pandas_select.isna().sum()

WAFER_ID                   0
OPE_NO                     0
INLINE_PARAMETER_ID        0
AVERAGE                    0
MAX_VAL                25897
MEDIAN                 25897
MIN_VAL                25897
STD_DEV                25897
PERCENTILE_25          25897
PERCENTILE_75          25897
SITE_COUNT             25897
label                      0
dtype: int64

In [16]:
# df_pandas_select[df_pandas_select['OPE_NO'] == '1V.EQW10'][['WAFER_ID', 'OPE_NO', 'INLINE_PARAMETER_ID', 'AVERAGE', 'MAX_VAL',
#        'MEDIAN', 'MIN_VAL', 'STD_DEV', 'PERCENTILE_25', 'PERCENTILE_75', 'SITE_COUNT', 'label']]

In [17]:
# df_pandas_select[df_pandas_select['OPE_NO'] == '1V.EQW10'][['SITE1_VAL', 'SITE2_VAL', 'SITE3_VAL', 'SITE4_VAL', 'SITE5_VAL', 'SITE6_VAL', 'SITE7_VAL',
# 'SITE8_VAL', 'SITE9_VAL', 'SITE10_VAL', 'SITE11_VAL', 'SITE12_VAL', 'SITE13_VAL', 'SITE14_VAL', 'SITE15_VAL', 'SITE16_VAL', 'SITE17_VAL']]

In [18]:
# df_pandas_select1.query("WAFER_ID == 'NAZ439-03' & OPE_NO == '1F.FQE10' & INLINE_PARAMETER_ID == 'TDS0'").to_dict()

In [19]:
df_pandas_select['WAFER_ID'].unique()

array(['NAZ439-03', 'NAZ703-08', 'NBX219-17', 'NAZ703-01', 'NAZ439-07',
       'NBX082-05', 'NAZ415-06', 'NBX082-16', 'NAZ439-06', 'NBX082-12',
       'NAZ703-09', 'NAZ415-08', 'NAZ415-12', 'NAZ415-13', 'NBX082-15'],
      dtype=object)

In [20]:
df_groupby = df_pandas_select.groupby(['OPE_NO', 'label'])['WAFER_ID'].nunique().unstack(fill_value=0).reset_index()
df_groupby.columns = ['OPER_NO',  'good_num', 'bad_num']
df_groupby_head = df_groupby.query("bad_num > 1").sort_values(['bad_num', 'good_num'], ascending=False).reset_index(drop=True)
df_groupby_head

     OPER_NO  good_num  bad_num
0   1C.CDG10         2       13
1   1U.CDG10         2       13
2   1U.CDG20         2       13
3   2U.CDG10         2       13
4   2U.CDG20         2       13
..       ...       ...      ...
82  TV.EQW10         1        3
83  1C.EQW10         0        2
84  1U.EQC10         0        2
85  1V.EQC10         0        2
86  XX.IQW01         0        2

[87 rows x 3 columns]

In [21]:
operno_list = list(df_groupby_head['OPER_NO'])
print(len(operno_list))
operno_list

87

['1C.CDG10',
 '1U.CDG10',
 '1U.CDG20',
 '2U.CDG10',
 '2U.CDG20',
 '3U.CDG10',
 '3U.CDG20',
 '6V.CDG10',
 '6V.CDG20',
 '7U.PQA20',
 '7U.PQX10',
 'PV.CDG10',
 'TM.PQX10',
 'TV.EQA20',
 'TV.PQX10',
 '2V.PQW10',
 '3U.PQW10',
 '6V.PQX10',
 'TV.CDG10',
 '1V.PQA10',
 '1V.PQX10',
 '1V.PQX20',
 '2U.PQA10',
 '2U.PQX10',
 '2V.PQX10',
 '3U.PQX10',
 '7U.EQA20',
 '7U.PQA10',
 '2V.PQX20',
 '7U.ECU10',
 'TM.EQA10',
 'PV.PQA10',
 '2V.PQA10',
 '7U.EQA10',
 'PV.PQX10',
 'TM.PQA10',
 '6V.PQW10',
 '7U.PQW10',
 'TM.PQW10',
 'TV.PQW10',
 'XX.PQX02',
 '6V.PQA10',
 'TV.PQA10',
 'PV.EQA10',
 '1U.EQW20',
 '1U.ECU10',
 '1V.ECU10',
 '2V.ECU10',
 '1V.EQW10',
 '2U.PQW10',
 '1C.PQX10',
 '1C.PQA10',
 '1U.PQX10',
 '1V.PQW10',
 '2U.EQW10',
 '3U.PQA10',
 '6V.EQA10',
 '1U.PQA10',
 '2U.CQC50',
 '3U.CQC10',
 'XX.EQW01',
 'XX.PQW01',
 'XX.PQW03',
 '1U.EQW10',
 '3U.EQW10',
 '7U.EQW10',
 '1C.PQW10',
 '1U.CQC10',
 '1U.CQC50',
 '1V.EQC30',
 '1V.PQX30',
 '2U.CQC10',
 '3U.CQC50',
 '6V.CQC10',
 '6V.CQC20',
 '6V.CQC30',
 '6V.CQC40',
 'XX.PQX01',
 '1U.PQW10',
 '2V.EQW10',
 '6V.EQW10',
 'TM.EQW10',
 'TV.EQW10',
 '1C.EQW10',
 '1U.EQC10',
 '1V.EQC10',
 'XX.IQW01']

---------------------

In [135]:
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.preprocessing import StandardScaler

In [24]:
def process_missing_values(df, columns_to_process, threshold=0.6):
    df_processed = df.copy()
    for column in columns_to_process:
        # 计算当前列的缺失值比例
        missing_percentage = df[column].isnull().mean()
        # 如果缺失值比例超过阈值，删除该列；否则用均值填充
        if missing_percentage > threshold:
            df_processed = df_processed.drop(columns=[column])
        else:
            df_processed[column] = df_processed[column].fillna(df_processed[column].mean())
    return df_processed

In [166]:
oper = operno_list[15]
df_pandas_select_specific_operno = df_pandas_select.query(f"OPE_NO == '{oper}'")
df_pandas_select_specific_operno

,WAFER_ID,OPE_NO,INLINE_PARAMETER_ID,AVERAGE,MAX_VAL,MEDIAN,MIN_VAL,STD_DEV,PERCENTILE_25,PERCENTILE_75,SITE_COUNT,label
569,NAZ703-08,2V.PQW10,01W0,0.064400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
570,NAZ703-08,2V.PQW10,02W0,0.065300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
571,NAZ703-08,2V.PQW10,03W0,0.063800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
572,NAZ703-08,2V.PQW10,04W0,0.064100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
573,NAZ703-08,2V.PQW10,05W0,0.064100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...
29812,NBX082-15,2V.PQW10,DNW07,0.065900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
29813,NBX082-15,2V.PQW10,DPW0,0.066044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
29814,NBX082-15,2V.PQW10,DPW1,0.105444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
29815,NBX082-15,2V.PQW10,XSIG,0.001900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
29816,NBX082-15,2V.PQW10,YSIG,0.001400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [167]:
columns_to_process = ['AVERAGE', 'MAX_VAL', 'MEDIAN', 'MIN_VAL', 'STD_DEV', 'PERCENTILE_25', 'PERCENTILE_75']
df_pandas_select_specific_operno = process_missing_values(df=df_pandas_select_specific_operno, columns_to_process=columns_to_process, threshold=0.6)
df_pandas_select_specific_operno

        WAFER_ID    OPE_NO INLINE_PARAMETER_ID   AVERAGE  SITE_COUNT  label
569    NAZ703-08  2V.PQW10                01W0  0.064400         NaN      1
570    NAZ703-08  2V.PQW10                02W0  0.065300         NaN      1
571    NAZ703-08  2V.PQW10                03W0  0.063800         NaN      1
572    NAZ703-08  2V.PQW10                04W0  0.064100         NaN      1
573    NAZ703-08  2V.PQW10                05W0  0.064100         NaN      1
...          ...       ...                 ...       ...         ...    ...
29812  NBX082-15  2V.PQW10               DNW07  0.065900         NaN      1
29813  NBX082-15  2V.PQW10                DPW0  0.066044         NaN      1
29814  NBX082-15  2V.PQW10                DPW1  0.105444         NaN      1
29815  NBX082-15  2V.PQW10                XSIG  0.001900         NaN      1
29816  NBX082-15  2V.PQW10                YSIG  0.001400         NaN      1

[1554 rows x 6 columns]

In [168]:
values_list = df_pandas_select_specific_operno.columns.difference(['WAFER_ID', 'OPE_NO', 'INLINE_PARAMETER_ID', 'SITE_COUNT', 'label'])

pivot_result = df_pandas_select_specific_operno.pivot_table(index=['WAFER_ID', 'label'], 
                                                            columns=['OPE_NO', 'INLINE_PARAMETER_ID'],
                                                            values=values_list)
pivot_result.columns = pivot_result.columns.map('#'.join)
pivot_result = process_missing_values(df=pivot_result, columns_to_process=pivot_result.columns, threshold=0.6)
pivot_result = pivot_result.reset_index(drop=False)
pivot_result

,WAFER_ID,label,AVERAGE#2V.PQW10#01W0,AVERAGE#2V.PQW10#02W0,AVERAGE#2V.PQW10#03W0,AVERAGE#2V.PQW10#04W0,AVERAGE#2V.PQW10#05W0,AVERAGE#2V.PQW10#06W0,AVERAGE#2V.PQW10#07W0,AVERAGE#2V.PQW10#08W0,...,AVERAGE#2V.PQW10#DNW05,AVERAGE#2V.PQW10#DNW06,AVERAGE#2V.PQW10#DNW07,AVERAGE#2V.PQW10#DNW08,AVERAGE#2V.PQW10#DNW09,AVERAGE#2V.PQW10#DNW10,AVERAGE#2V.PQW10#DNW11,AVERAGE#2V.PQW10#DNW12,AVERAGE#2V.PQW10#XSIG,AVERAGE#2V.PQW10#YSIG
0,NAZ415-06,1,0.0649,0.0660,0.0658,0.0653,0.0659,0.0658,0.0635,0.0671,...,0.0651,0.0039,0.064000,0.0043,0.064900,0.003900,0.0587,0.0047,0.0027,0.0057
1,NAZ415-08,1,0.0658,0.0650,0.0655,0.0658,0.0666,0.0672,0.0647,0.0652,...,0.0652,0.0040,0.064500,0.0041,0.065300,0.003900,0.0591,0.0043,0.0026,0.0060
2,NAZ415-12,1,0.0658,0.0658,0.0651,0.0648,0.0649,0.0652,0.0645,0.0665,...,0.0653,0.0040,0.064000,0.0042,0.065100,0.003900,0.0592,0.0045,0.0021,0.0059
3,NAZ415-13,1,0.0650,0.0649,0.0645,0.0651,0.0654,0.0659,0.0650,0.0671,...,0.0651,0.0039,0.064300,0.0041,0.065000,0.003900,0.0591,0.0046,0.0023,0.0059
4,NAZ439-03,0,0.0655,0.0660,0.0655,0.0652,0.0655,0.0653,0.0638,0.0659,...,0.0655,0.0039,0.064100,0.0042,0.065300,0.003900,0.0591,0.0048,0.0021,0.0064
5,NAZ439-06,1,0.0652,0.0658,0.0655,0.0656,0.0655,0.0652,0.0653,0.0644,...,0.0651,0.0039,0.063600,0.0041,0.064900,0.003900,0.0584,0.0043,0.0017,0.0065
6,NAZ439-07,0,0.0646,0.0644,0.0655,0.0642,0.0649,0.0645,0.0632,0.0654,...,0.0648,0.0040,0.063600,0.0043,0.064400,0.003900,0.0574,0.0046,0.0023,0.0044
7,NAZ703-08,1,0.0644,0.0653,0.0638,0.0641,0.0641,0.0637,0.0622,0.0654,...,0.0647,0.0039,0.063700,0.0042,0.064300,0.004000,0.0593,0.0043,0.0024,0.0068
8,NAZ703-09,1,0.0647,0.0639,0.0654,0.0641,0.0646,0.0647,0.0637,0.0648,...,0.0645,0.0039,0.063300,0.0043,0.064600,0.004000,0.0589,0.0044,0.0017,0.0048
9,NBX082-05,1,0.0649,0.0661,0.0675,0.0654,0.0647,0.0652,0.0659,0.0652,...,0.0659,0.0610,0.065400,0.0042,0.064867,0.003922,0.0588,0.0045,0.0025,0.0019
10,NBX082-12,1,0.0642,0.0653,0.0655,0.0663,0.0662,0.0648,0.0667,0.0652,...,0.0658,0.0614,0.065100,0.0042,0.064867,0.003922,0.0588,0.0045,0.0025,0.0027
11,NBX082-15,1,0.0653,0.0658,0.0661,0.0656,0.0663,0.0659,0.0669,0.0657,...,0.0664,0.0595,0.065900,0.0042,0.064867,0.003922,0.0588,0.0045,0.0019,0.0014
12,NBX082-16,1,0.0649,0.0656,0.0661,0.0653,0.0652,0.0652,0.0655,0.0657,...,0.0659,0.0599,0.065400,0.0042,0.064867,0.003922,0.0588,0.0045,0.0021,0.0016
13,NBX219-17,1,0.0670,0.0639,0.0664,0.0663,0.0647,0.0651,0.0667,0.0678,...,0.0684,0.0763,0.064377,0.0042,0.064867,0.003922,0.0588,0.0045,0.0032,0.0021

In [173]:
label = np.array(pivot_result['label'])

In [136]:
# import sklearn
# sklearn.__version__

In [181]:
# 定义自变量
df_pivot_all = pivot_result.copy() 
x_train = df_pivot_all[df_pivot_all.columns.difference(['WAFER_ID', 'label']).tolist()]

In [182]:
hierarchical = AgglomerativeClustering(n_clusters=2)
predict = hierarchical.fit_predict(np.array(x_train))
predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [179]:
flipped_label = 1 - label
print(flipped_label)

[0 0 0 0 1 0 1 0 0 0 0 0 0 0]

In [180]:
from sklearn.metrics import accuracy_score

conf_matrix = accuracy_score(flipped_label, predict)
print(conf_matrix)

0.5

In [36]:
# 定义自变量
df_pivot_all = pivot_result.copy() 
x_train = df_pivot_all[df_pivot_all.columns.difference(['WAFER_ID', 'label']).tolist()]

n_components = min(min(x_train.shape[0], (x_train.shape[1])-1), 5)
print(n_components)
model = pca(n_components=n_components, verbose=None)
results = model.fit_transform(x_train)
res_top = results['topfeat']
res_top_select = res_top[res_top['type'] == 'best'][['feature', 'loading']]
res_top_select = res_top_select.drop_duplicates()
res_top_select['importance'] = abs(res_top_select['loading'])
res_top_select = res_top_select.rename(columns={'feature': 'features'})
res_top_select = res_top_select.drop("loading", axis=1)
res_top_select

5

                features  importance
0  AVERAGE#XX.PQX02#MPW0    0.871506
1  AVERAGE#XX.PQX02#WAW0    0.605697
2  AVERAGE#XX.PQX02#WAW0    0.675747
3  AVERAGE#XX.PQX02#SAW0    0.597546
4  AVERAGE#XX.PQX02#WBW0    0.451323

----------------------------

In [37]:
res_top_select_all = pd.DataFrame()

for i in range(len(operno_list)): 
    oper = operno_list[i]
    print(f"*************当前站点是{oper}*************")
    df_pandas_select_specific_operno = df_pandas_select.query(f"OPE_NO == '{oper}'")
    
    columns_to_process = ['AVERAGE', 'MAX_VAL', 'MEDIAN', 'MIN_VAL', 'STD_DEV', 'PERCENTILE_25', 'PERCENTILE_75']
    df_pandas_select_specific_operno = process_missing_values(df=df_pandas_select_specific_operno, 
                                                              columns_to_process=columns_to_process, 
                                                              threshold=0.6)

    values_list = df_pandas_select_specific_operno.columns.difference(['WAFER_ID', 'OPE_NO', 'INLINE_PARAMETER_ID', 'SITE_COUNT', 'label'])
    pivot_result = df_pandas_select_specific_operno.pivot_table(index=['WAFER_ID', 'label'], 
                                                                columns=['OPE_NO', 'INLINE_PARAMETER_ID'],
                                                                values=values_list)
    pivot_result.columns = pivot_result.columns.map('#'.join)
    pivot_result = process_missing_values(df=pivot_result, columns_to_process=pivot_result.columns, threshold=0.6)
    pivot_result = pivot_result.reset_index(drop=False)

    # 定义自变量
    df_pivot_all = pivot_result.copy()
    
    x_train = df_pivot_all[df_pivot_all.columns.difference(['WAFER_ID', 'label']).tolist()]
    print("x_train维度是", x_train.shape)
    
    n_components = min(min(x_train.shape)-1, 5)
    print("降维个数是", n_components)
    
    model = pca(n_components=n_components, verbose=None)
    results = model.fit_transform(x_train)
    res_top = results['topfeat']
    res_top_select = res_top[res_top['type'] == 'best'][['feature', 'loading']]
    res_top_select = res_top_select.drop_duplicates()
    res_top_select['importance'] = abs(res_top_select['loading'])
    res_top_select = res_top_select.rename(columns={'feature': 'features'})
    res_top_select = res_top_select.drop("loading", axis=1)
    res_top_select_all = pd.concat([res_top_select_all, res_top_select], axis=0)

*************当前站点是1C.CDG10*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是1U.CDG10*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是1U.CDG20*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是2U.CDG10*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是2U.CDG20*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是3U.CDG10*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是3U.CDG20*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是6V.CDG10*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是6V.CDG20*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是7U.PQA20*************
x_train维度是 (15, 5)
降维个数是 4
*************当前站点是7U.PQX10*************
x_train维度是 (15, 518)
降维个数是 5
*************当前站点是PV.CDG10*************
x_train维度是 (15, 10)
降维个数是 5
*************当前站点是TM.PQX10*************
x_train维度是 (15, 518)
降维个数是 5
*************当前站点是TV.EQA20*************
x_train维度是 (15, 5)
降维个数是 4
*************当前站点是TV.PQX10*************
x_train维度是 (15, 518)
降维个数是 5
*************当前站点是2V.PQW10*************
x_train维度是 (14, 129)
降维个数是 5
*************当前站点是3U.PQW10*************
x_train维度是 (14, 72)
降维个数是 5
*************当前站点是6V.PQX10*************
x_train维度是 (14, 518)
降维个数是 5
*************当前站点是TV.CDG10*************
x_train维度是 (14, 10)
降维个数是 5
*************当前站点是1V.PQA10*************
x_train维度是 (13, 5)
降维个数是 4
*************当前站点是1V.PQX10*************
x_train维度是 (13, 74)
降维个数是 5
*************当前站点是1V.PQX20*************
x_train维度是 (13, 518)
降维个数是 5
*************当前站点是2U.PQA10*************
x_train维度是 (13, 5)
降维个数是 4
*************当前站点是2U.PQX10*************
x_train维度是 (13, 74)
降维个数是 5
*************当前站点是2V.PQX10*************
x_train维度是 (13, 74)
降维个数是 5
*************当前站点是3U.PQX10*************
x_train维度是 (13, 74)
降维个数是 5
*************当前站点是7U.EQA20*************
x_train维度是 (13, 5)
降维个数是 4
*************当前站点是7U.PQA10*************
x_train维度是 (13, 5)
降维个数是 4
*************当前站点是2V.PQX20*************
x_train维度是 (12, 518)
降维个数是 5
*************当前站点是7U.ECU10*************
x_train维度是 (12, 21)
降维个数是 5
*************当前站点是TM.EQA10*************
x_train维度是 (12, 5)
降维个数是 4
*************当前站点是PV.PQA10*************
x_train维度是 (11, 5)
降维个数是 4
*************当前站点是2V.PQA10*************
x_train维度是 (10, 5)
降维个数是 4
*************当前站点是7U.EQA10*************
x_train维度是 (11, 5)
降维个数是 4
*************当前站点是PV.PQX10*************
x_train维度是 (11, 518)
降维个数是 5
*************当前站点是TM.PQA10*************
x_train维度是 (11, 5)
降维个数是 4
*************当前站点是6V.PQW10*************
x_train维度是 (10, 165)
降维个数是 5
*************当前站点是7U.PQW10*************
x_train维度是 (10, 93)
降维个数是 5
*************当前站点是TM.PQW10*************
x_train维度是 (10, 39)
降维个数是 5
*************当前站点是TV.PQW10*************
x_train维度是 (10, 39)
降维个数是 5
*************当前站点是XX.PQX02*************
x_train维度是 (9, 88)
降维个数是 5
*************当前站点是6V.PQA10*************
x_train维度是 (10, 5)
降维个数是 4
*************当前站点是TV.PQA10*************
x_train维度是 (10, 5)
降维个数是 4
*************当前站点是PV.EQA10*************
x_train维度是 (9, 5)
降维个数是 4
*************当前站点是1U.EQW20*************
x_train维度是 (8, 52)
降维个数是 5
*************当前站点是1U.ECU10*************
x_train维度是 (7, 35)
降维个数是 5
*************当前站点是1V.ECU10*************
x_train维度是 (7, 21)
降维个数是 5
*************当前站点是2V.ECU10*************
x_train维度是 (7, 28)
降维个数是 5
*************当前站点是1V.EQW10*************
x_train维度是 (8, 53)
降维个数是 5
*************当前站点是2U.PQW10*************
x_train维度是 (8, 92)
降维个数是 5
*************当前站点是1C.PQX10*************
x_train维度是 (6, 70)
降维个数是 5
*************当前站点是1C.PQA10*************
x_train维度是 (7, 5)
降维个数是 4
*************当前站点是1U.PQX10*************
x_train维度是 (7, 518)
降维个数是 5
*************当前站点是1V.PQW10*************
x_train维度是 (7, 219)
降维个数是 5
*************当前站点是2U.EQW10*************
x_train维度是 (7, 53)
降维个数是 5
*************当前站点是3U.PQA10*************
x_train维度是 (7, 5)
降维个数是 4
*************当前站点是6V.EQA10*************
x_train维度是 (7, 5)
降维个数是 4
*************当前站点是1U.PQA10*************
x_train维度是 (5, 5)
降维个数是 4
*************当前站点是2U.CQC50*************
x_train维度是 (5, 10)
降维个数是 4
*************当前站点是3U.CQC10*************
x_train维度是 (5, 5)
降维个数是 4
*************当前站点是XX.EQW01*************
x_train维度是 (5, 92)
降维个数是 4
*************当前站点是XX.PQW01*************
x_train维度是 (5, 170)
降维个数是 4
*************当前站点是XX.PQW03*************
x_train维度是 (5, 206)
降维个数是 4
*************当前站点是1U.EQW10*************
x_train维度是 (6, 53)
降维个数是 5
*************当前站点是3U.EQW10*************
x_train维度是 (6, 94)
降维个数是 5
*************当前站点是7U.EQW10*************
x_train维度是 (5, 94)
降维个数是 4
*************当前站点是1C.PQW10*************
x_train维度是 (4, 51)
降维个数是 3
*************当前站点是1U.CQC10*************
x_train维度是 (4, 5)
降维个数是 3
*************当前站点是1U.CQC50*************
x_train维度是 (4, 5)
降维个数是 3
*************当前站点是1V.EQC30*************
x_train维度是 (4, 18)
降维个数是 3
*************当前站点是1V.PQX30*************
x_train维度是 (4, 658)
降维个数是 3
*************当前站点是2U.CQC10*************
x_train维度是 (4, 5)
降维个数是 3
*************当前站点是3U.CQC50*************
x_train维度是 (4, 10)
降维个数是 3
*************当前站点是6V.CQC10*************
x_train维度是 (4, 5)
降维个数是 3
*************当前站点是6V.CQC20*************
x_train维度是 (4, 10)
降维个数是 3
*************当前站点是6V.CQC30*************
x_train维度是 (4, 13)
降维个数是 3
*************当前站点是6V.CQC40*************
x_train维度是 (4, 14)
降维个数是 3
*************当前站点是XX.PQX01*************
x_train维度是 (4, 74)
降维个数是 3
*************当前站点是1U.PQW10*************
x_train维度是 (5, 73)
降维个数是 4
*************当前站点是2V.EQW10*************
x_train维度是 (5, 79)
降维个数是 4
*************当前站点是6V.EQW10*************
x_train维度是 (4, 89)
降维个数是 3
*************当前站点是TM.EQW10*************
x_train维度是 (4, 40)
降维个数是 3
*************当前站点是TV.EQW10*************
x_train维度是 (4, 31)
降维个数是 3
*************当前站点是1C.EQW10*************
x_train维度是 (2, 106)
降维个数是 1
*************当前站点是1U.EQC10*************
x_train维度是 (2, 49)
降维个数是 1
*************当前站点是1V.EQC10*************
x_train维度是 (2, 19)
降维个数是 1
*************当前站点是XX.IQW01*************
x_train维度是 (2, 123)
降维个数是 1

In [38]:
res_top_select_all.shape

(363, 2)

In [39]:
# res_top_select_all1 = res_top_select_all[res_top_select_all['features'].str.contains('AVERAGE')]
# res_top_select_all1.shape

In [40]:
def split_features(df, index) -> str:
    """
    param df: RandomForest建模后的feature_importance_table
    param index: 顺序值
    return: 字段属性值
    """
    return df['features'].apply(lambda x: x.split('#')[index])

In [41]:
def get_split_feature_importance_table(df):
    df['STATISTIC_RESULT'] = split_features(df, 0)
    df['OPER_NO'] = split_features(df, 1)
    df['INLINE_PARAMETER_ID'] = split_features(df, 2)
    
    df = df.drop(['features', 'STATISTIC_RESULT'], axis=1).reset_index(drop=True)
    return df

In [43]:
split_table = get_split_feature_importance_table(res_top_select_all) 
print(split_table.shape)
split_table_grpby = split_table.groupby(['OPER_NO', 'INLINE_PARAMETER_ID'])['importance'].sum().reset_index(drop=False)
split_table_grpby.shape

(363, 3)

(335, 3)

In [44]:
split_table_grpby.sort_values('importance', ascending=False).reset_index(drop=True).head(30)

     OPER_NO INLINE_PARAMETER_ID  importance
0   1V.ECU10                TGS2    2.748250
1   7U.ECU10                FGS1    2.000000
2   7U.ECU10                TGS1    2.000000
3   2V.ECU10                T1S2    1.910730
4   2V.ECU10                TGS2    1.721497
5   2U.CQC50                THW2    1.656931
6   1U.CDG10                TSW0    1.357991
7   7U.PQW10                18W0    1.346874
8   2U.CQC10                THW1    1.339157
9   1C.PQX10                SAW0    1.292641
10  XX.PQX02                WAW0    1.281444
11  6V.CQC10                TLW1    1.263052
12  TV.PQX10                SAW0    1.262952
13  1U.ECU10                TGS2    1.174102
14  1V.EQW10                40W0    1.045640
15  7U.PQA20                SNW0    1.000000
16  7U.PQA10                SNW0    1.000000
17  PV.PQA10                SNW0    1.000000
18  TV.PQA10                SNW0    1.000000
19  7U.ECU10                TGS2    1.000000
20  PV.EQA10                MSW0    1.000000
21  PV.PQA10                MEW0    1.000000
22  PV.PQA10                MFW0    1.000000
23  PV.PQA10                MSW0    1.000000
24  1U.PQA10                MFW0    1.000000
25  1V.PQA10                MSW0    1.000000
26  1U.PQA10                MEW0    1.000000
27  TV.EQA20                MFW0    1.000000
28  1U.PQA10                MSW0    1.000000
29  1U.PQA10                SNW0    1.000000

In [46]:
# split_table_grpby[split_table_grpby['OPER_NO'].str.contains('V.EQW')]